### ISSUE TITLE
DSC task to enable proxy for updated applications on Windows is not idempotent

### ISSUE THREAD

**Issue by bcdonadio** [stone-payments/ansible-proxy#7]
The xProxySettings DSC module is not idempotent (at least from the Ansible perspective) and its always throwing changes even when there's no underlying detectable change on the proxy config state. This should be investigated and fixed.

https://github.com/stone-payments/ansible-proxy/blob/65a78365798c04c562d7f85a5bcc324b9a700d0f/tasks/windows/enable.yml#L30-L40

**Comment by renatocmaia** [comment]
We don't use win_dcs module more.
